version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - API_PORT=8081
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=api1
    networks:
      - networkNames
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.22"
          memory: "29MB"

  api02:
    <<: *api 
    hostname: api02
    environment:
      - API_PORT=8082
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=api2
    networks:
      - networkNames
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - networkNames
    deploy:
      resources:
        limits:
          cpus: "0.26"
          memory: "22MB"

  db:
    image: mysql:8.0
    container_name: mysql-api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - networkNames
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "470MB"


  datadog:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=5989fd4e6d9494051a29baaca069daf0
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_HOSTNAME=datadog-agent
    ports:
      - "8126:8126"  # Porta APM
    networks:
      - networkNames
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Para coletar métricas de containers
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "200MB"



volumes:
  mysql_data:

networks:
  networkNames:
    driver: bridge
